### ISSUE TITLE
  can you add a new item

### ISSUE THREAD

**Issue by slowvic** [arcticsn0w/arcticsn0w.github.io#2]
0.0.0.0 wo.iuni.com.cn
this is a site of CMCC(a SP) in China，which can populate an ad banner at the bottom of almost every app。
can you add the item above to the #OtherAnnoyingStuff list ？ thank you.

**Comment by Diabyte** [comment]
i downloaded killios.deb but data part of deb package is empty!

**Comment by arcticsn0w** [comment]
That's normal.

**Comment by arcticsn0w** [comment]
As to slowvic; email ReddestDream.
